---
R1:
    hostname: 10.10.10.14
    groups:
        - Router
    data:
        host: R1
        as_number: 200
R2:
    hostname: 10.10.10.13
    groups:
        - Router
    data:
        host: R2
        as_number: 200